import "./globals.css";
import Providers from "@utils/provider";
import font, { inter, poppins } from "@utils/fonts";
import { ThemeProvider } from "../context/ThemeContext";
import PaletteSwitcher from "@components/PaletteSwitcher";

export const metadata = {
  title: "FarmExpo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body className={`font-inter`}>
        <ThemeProvider>
          <Providers>{children}</Providers>
          <PaletteSwitcher />
        </ThemeProvider>
      </body>
    </html>
  );
}
